"""crate all tables for quizzes

Revision ID: 3ef91c575a8d
Revises: c48265847bd6
Create Date: 2026-03-03 15:48:52.854654

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "3ef91c575a8d"
down_revision: Union[str, Sequence[str], None] = "c48265847bd6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "quizzes",
        sa.Column("quiz_id", sa.Integer(), nullable=False),
        sa.Column("slug", sa.String(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("quiz_id"),
        sa.UniqueConstraint("slug"),
    )
    op.create_table(
        "quiz_attempts",
        sa.Column("attempt_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("quiz_id", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "IN_PROGRESS",
                "FINISHED",
                "CANCELLED",
                name="quiz_attempt_status",
            ),
            nullable=False,
        ),
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("seed", sa.Integer(), nullable=False),
        sa.Column("result_score", sa.Integer(), nullable=True),
        sa.Column("result_percent", sa.Integer(), nullable=True),
        sa.CheckConstraint(
            "result_percent BETWEEN 0 AND 100", name="ck_attempt_percent_range"
        ),
        sa.ForeignKeyConstraint(
            ["quiz_id"], ["quizzes.quiz_id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.user_id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("attempt_id"),
    )
    op.create_index(
        op.f("ix_quiz_attempts_quiz_id"),
        "quiz_attempts",
        ["quiz_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_quiz_attempts_user_id"),
        "quiz_attempts",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "quiz_questions",
        sa.Column("question_id", sa.Integer(), nullable=False),
        sa.Column("quiz_id", sa.Integer(), nullable=False),
        sa.Column("order", sa.Integer(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("is_reverse", sa.Boolean(), nullable=False),
        sa.Column("dimension", sa.String(length=10), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["quiz_id"], ["quizzes.quiz_id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("question_id"),
        sa.UniqueConstraint("quiz_id", "order", name="uq_quiz_id_order"),
    )
    op.create_index(
        op.f("ix_quiz_questions_quiz_id"),
        "quiz_questions",
        ["quiz_id"],
        unique=False,
    )
    op.create_table(
        "answer_options",
        sa.Column("option_id", sa.Integer(), nullable=False),
        sa.Column("question_id", sa.Integer(), nullable=False),
        sa.Column("order", sa.Integer(), nullable=False),
        sa.Column("label", sa.String(length=128), nullable=False),
        sa.Column("value", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            '"order" BETWEEN 1 AND 4', name="ck_answer_options_order_1_4"
        ),
        sa.CheckConstraint(
            "value BETWEEN 1 AND 4", name="ck_answer_options_value_1_4"
        ),
        sa.ForeignKeyConstraint(
            ["question_id"], ["quiz_questions.question_id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("option_id"),
        sa.UniqueConstraint(
            "question_id", "order", name="uq_answer_options_question_id_order"
        ),
        sa.UniqueConstraint(
            "question_id", "value", name="uq_answer_options_question_id_value"
        ),
    )
    op.create_index(
        op.f("ix_answer_options_question_id"),
        "answer_options",
        ["question_id"],
        unique=False,
    )
    op.create_table(
        "quiz_answers",
        sa.Column("answer_id", sa.Integer(), nullable=False),
        sa.Column("attempt_id", sa.Integer(), nullable=False),
        sa.Column("question_id", sa.Integer(), nullable=False),
        sa.Column("option_id", sa.Integer(), nullable=False),
        sa.Column("value", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "value BETWEEN 1 AND 4", name="ck_quiz_answers_value"
        ),
        sa.ForeignKeyConstraint(
            ["attempt_id"], ["quiz_attempts.attempt_id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["option_id"], ["answer_options.option_id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["question_id"], ["quiz_questions.question_id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("answer_id"),
        sa.UniqueConstraint(
            "attempt_id",
            "question_id",
            name="uq_quiz_answers_attempt_id_question_id",
        ),
    )
    op.create_index(
        op.f("ix_quiz_answers_attempt_id"),
        "quiz_answers",
        ["attempt_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_quiz_answers_option_id"),
        "quiz_answers",
        ["option_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_quiz_answers_question_id"),
        "quiz_answers",
        ["question_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_quiz_answers_question_id"), table_name="quiz_answers"
    )
    op.drop_index(op.f("ix_quiz_answers_option_id"), table_name="quiz_answers")
    op.drop_index(
        op.f("ix_quiz_answers_attempt_id"), table_name="quiz_answers"
    )
    op.drop_table("quiz_answers")
    op.drop_index(
        op.f("ix_answer_options_question_id"), table_name="answer_options"
    )
    op.drop_table("answer_options")
    op.drop_index(
        op.f("ix_quiz_questions_quiz_id"), table_name="quiz_questions"
    )
    op.drop_table("quiz_questions")
    op.drop_index(op.f("ix_quiz_attempts_user_id"), table_name="quiz_attempts")
    op.drop_index(op.f("ix_quiz_attempts_quiz_id"), table_name="quiz_attempts")
    op.drop_table("quiz_attempts")
    op.drop_table("quizzes")
    # ### end Alembic commands ###
